<a href="https://colab.research.google.com/github/Chinhan1532/AI_Class/blob/main/AI_W8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model = Perceptron()
model.fit(x,y)
model.score(x,y)

1.0

In [33]:
x1=[[0.6,0],[0.7,0],[0.5,0],[0.8,0],[0.49,0.4],[0.25,0.25]]
y1=model.predict(x1)
print(y1)
model.score(x1,y1)

[1 1 0 1 1 0]


1.0

In [54]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
iris = datasets.load_iris()
X=iris.data
y=iris.target
print(X[:5])
print(y[:5])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
Sc= StandardScaler()
Sc.fit(X_train)
X_train_Std=Sc.transform(X_train)
X_test_Std=Sc.transform(X_test)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [55]:
model=Perceptron(max_iter= 40, eta0=0.1, random_state=0)
model.fit(X_train_Std,y_train)
y_pred=model.predict(X_test_Std)
print(y_pred)
print(y_test)
print('Do chinh xac cua mo hinh:',accuracy_score(y_test,y_pred))

[1 1 1 2 0 0 2 2 1 2 0 0 2 0 2 2 2 0 1 0 0 1 2 0 1 1 2 2 0 0 1 2 1 2 2 0 0
 0 0 2 1 0 1 0 1]
[1 1 1 2 0 0 2 2 1 2 0 0 2 0 2 2 2 0 1 0 0 1 2 0 1 1 2 2 0 0 1 2 1 2 2 0 0
 0 0 2 1 0 2 0 1]
Do chinh xac cua mo hinh: 0.9777777777777777


In [59]:
import pandas as pd
url = '/content/crabs.csv'
data = pd.read_csv(url)
data.head()

speies sex  index  fontallip  rearwidth  length  width  depth
0      B   M      1        8.1        6.7    16.1   19.0    7.0
1      B   M      2        8.8        7.7    18.1   20.8    7.4
2      B   M      3        9.2        7.8    19.0   22.4    7.7
3      B   M      4        9.6        7.9    20.1   23.1    8.2
4      B   M      5        9.8        8.0    20.3   23.0    8.2

In [70]:
import numpy as np
data = pd.read_csv('/content/crabs.csv')
crab_8=data
crab_8.sex = crab_8.sex.apply(lambda x: x.replace("M","1"))
crab_8.sex = crab_8.sex.apply(lambda x: x.replace("F","0"))
crab_8.speies = crab_8.speies.apply(lambda x: x.replace("O","1"))
crab_8.speies = crab_8.speies.apply(lambda x: x.replace("B","0"))
print(data)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        0   1      1        8.1        6.7    16.1   19.0    7.0
1        0   1      2        8.8        7.7    18.1   20.8    7.4
2        0   1      3        9.2        7.8    19.0   22.4    7.7
3        0   1      4        9.6        7.9    20.1   23.1    8.2
4        0   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      1   0     46       21.4       18.0    41.2   46.2   18.7
196      1   0     47       21.7       17.1    41.7   47.2   19.6
197      1   0     48       21.9       17.2    42.6   47.4   19.5
198      1   0     49       22.5       17.2    43.0   48.7   19.8
199      1   0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]
